name: CI Ubuntu
on: [push, pull_request]
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        - '5.30'
    container:
      image: perl:${{matrix.perl-version}}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: perl -V
      run: perl -V
    - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
      run: cpanm -n App::cpanminus ExtUtils::MakeMaker
    - name: Install dependencies
      run: |
        cpanm -n --installdeps .
        npm i -D webpack webpack-cli
    - name: Run build production test
      run: prove -vl
      env:
        TEST_BUILD_ASSETS: 1
        MOJO_WEBPACK_DEBUG: 1